version: '3.7'
services:
  tiqo:
    container_name: tiqo
    hostname: tiqo
    build: .
    volumes:
      - ./:/TiQO
    working_dir: /TiQO/QontoOdooDjango
    # ports:
      # - 8005:8005
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend

      - traefik.http.routers.tiqo.tls.certresolver=myresolver
      - traefik.http.routers.tiqo.rule=Host(`$DOMAIN`)
      - traefik.http.services.tiqo.loadbalancer.server.port=8005

    # command: "sleep 5d"
    command: "poetry run bash launch.sh"
    networks:
      - frontend
      
networks:
  frontend:
    external: true
