version: '3.7'
services:
  tiqo:
    container_name: tiqo
    hostname: tiqo
    build: .
    volumes:
      - ./:/TiQO
    working_dir: /TiQO/QontoOdooDjango
    # ports:
      # - 8005:8005
    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend

      - traefik.http.routers.test_machine.tls.certresolver=myresolver
      - traefik.http.routers.test_machine.rule=Host(`$DOMAIN`)
      - traefik.http.services.test_machine.loadbalancer.server.port=8005

    command: "sleep 5d"
    # command: "poetry run bash launch.sh"
