# Generated by Django 4.1.7 on 2023-03-09 13:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAnalyticAccount',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('id_odoo', models.SmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AccountAnalyticGroup',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('id_odoo', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountJournal',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('id_odoo', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qonto_login', models.CharField(max_length=100)),
                ('qonto_apikey', models.CharField(max_length=100)),
                ('odoo_url', models.URLField()),
                ('odoo_login', models.CharField(max_length=100)),
                ('odoo_apikey', models.CharField(max_length=100)),
                ('odoo_dbname', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Iban',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('iban', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('odoo_analytic_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiqo_parser.accountanalyticaccount')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiqo_parser.label')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('emitted_at', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
                ('amount_cents', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('note', models.TextField(blank=True, null=True)),
                ('label', models.CharField(max_length=100)),
                ('vat_amount_cents', models.IntegerField()),
                ('initiator_id', models.UUIDField()),
                ('card_last_digits', models.CharField(max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiqo_parser.category')),
                ('iban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiqo_parser.iban')),
                ('label_ids', models.ManyToManyField(related_name='transactions', to='tiqo_parser.label')),
            ],
        ),
        migrations.AddField(
            model_name='accountanalyticaccount',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiqo_parser.accountanalyticgroup'),
        ),
    ]
