# Generated by Django 4.1.7 on 2023-03-23 11:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAccount',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('id_odoo', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountAnalyticAccount',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('id_odoo', models.SmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AccountAnalyticGroup',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('id_odoo', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountJournal',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('id_odoo', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qonto_login', models.CharField(max_length=100)),
                ('qonto_apikey', models.CharField(max_length=100)),
                ('odoo_url', models.URLField()),
                ('odoo_login', models.CharField(max_length=100)),
                ('odoo_apikey', models.CharField(max_length=100)),
                ('odoo_dbname', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Iban',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('iban', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Compte Qonto',
                'verbose_name_plural': 'Comptes Qonto',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('odoo_account_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiqo_parser.accountaccount')),
                ('odoo_analytic_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiqo_parser.accountanalyticaccount')),
            ],
            options={
                'verbose_name': 'Label Qonto',
                'verbose_name_plural': 'Labels Qonto',
            },
        ),
        migrations.CreateModel(
            name='OdooArticles',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('id_odoo', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OdooContact',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('id_odoo', models.SmallIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('type', models.CharField(choices=[('M', 'membership'), ('B', 'beneficiarie')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='QontoContact',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('type', models.CharField(choices=[('M', 'User Qonto'), ('B', 'Bénéficiaire')], max_length=1)),
                ('odoo_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiqo_parser.odoocontact')),
            ],
            options={
                'verbose_name': 'Contact Qonto',
                'verbose_name_plural': 'Contacts Qonto',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('transaction_id', models.CharField(max_length=100)),
                ('emitted_at', models.DateTimeField(verbose_name='Emission')),
                ('side', models.CharField(choices=[('D', 'debit'), ('C', 'credit')], max_length=1, verbose_name='Sens')),
                ('status', models.CharField(max_length=100)),
                ('amount_cents', models.IntegerField(verbose_name='Montant (cts)')),
                ('currency', models.CharField(max_length=3)),
                ('note', models.TextField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Libellé')),
                ('vat_amount_cents', models.IntegerField(blank=True, default=0, null=True)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('card_last_digits', models.CharField(blank=True, max_length=4, null=True)),
                ('uuid_external_transfer', models.UUIDField(blank=True, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('odoo_sended', models.BooleanField(default=False)),
                ('odoo_invoice_id', models.IntegerField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_transactions', to='tiqo_parser.qontocontact', verbose_name='Bénéficiaire')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiqo_parser.category')),
                ('iban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiqo_parser.iban', verbose_name='Compte')),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiator_transactions', to='tiqo_parser.qontocontact', verbose_name='Initiateur')),
                ('label_ids', models.ManyToManyField(related_name='transactions', to='tiqo_parser.label')),
            ],
            options={
                'verbose_name': 'Transaction Qonto',
                'verbose_name_plural': 'Transactions Qonto',
            },
        ),
        migrations.AddField(
            model_name='label',
            name='odoo_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiqo_parser.odooarticles'),
        ),
        migrations.AddField(
            model_name='label',
            name='odoo_journal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiqo_parser.accountjournal'),
        ),
        migrations.AddField(
            model_name='label',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiqo_parser.label'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('url_qonto', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('transactions', models.ManyToManyField(related_name='attachments', to='tiqo_parser.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='accountanalyticaccount',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiqo_parser.accountanalyticgroup'),
        ),
    ]
