# Generated by Django 4.1.7 on 2023-03-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiqo_parser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
    ]
