# Generated by Django 4.1.7 on 2023-03-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiqo_parser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='odoo_api',
            new_name='odoo_apikey',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='qonto_api',
            new_name='qonto_apikey',
        ),
    ]
