# Generated by Django 4.1.7 on 2023-03-09 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiqo_parser', '0002_remove_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='card_last_digits',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiqo_parser.category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
