# Generated by Django 4.1.7 on 2023-03-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiqo_parser', '0002_rename_odoo_api_configuration_odoo_apikey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='odoo_dbname',
            field=models.CharField(default='tibillet', max_length=100),
            preserve_default=False,
        ),
    ]
