# Generated by Django 4.1.7 on 2023-03-08 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tiqo_parser', '0003_configuration_odoo_dbname'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountJournal',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('id_odoo', models.SmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
