# Generated by Django 4.1.7 on 2023-03-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiqo_parser', '0004_alter_transaction_vat_amount_cents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='initiator_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
