# Generated by Django 4.1.7 on 2023-03-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiqo_parser', '0005_alter_transaction_initiator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='vat_amount_cents',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
