# Generated by Django 4.1.7 on 2023-03-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiqo_parser', '0006_alter_transaction_vat_amount_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='side',
            field=models.CharField(choices=[('D', 'debit'), ('C', 'credit')], default='C', max_length=1),
            preserve_default=False,
        ),
    ]
