# Generated by Django 4.1.7 on 2023-03-10 10:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tiqo_parser', '0009_rename_name_contact_first_name_contact_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FilePathField(allow_folders=True, path='/home/slaan/Gits/Qonto-to-Odoo/QontoOdooDjango/www/media', recursive=True)),
                ('name', models.CharField(max_length=100)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tiqo_parser.transaction')),
            ],
        ),
    ]
