# Generated by Django 4.1.7 on 2023-03-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiqo_parser', '0010_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='file',
            new_name='filepath',
        ),
    ]
