# Generated by Django 4.1.7 on 2023-03-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiqo_parser', '0011_rename_file_attachment_filepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='transaction',
        ),
        migrations.AddField(
            model_name='attachment',
            name='transactions',
            field=models.ManyToManyField(related_name='attachments', to='tiqo_parser.transaction'),
        ),
    ]
