# Generated by Django 4.1.7 on 2023-03-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiqo_parser', '0012_remove_attachment_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='url_qonto',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='filepath',
            field=models.FilePathField(allow_folders=True, blank=True, null=True, path='/home/slaan/Gits/Qonto-to-Odoo/QontoOdooDjango/www/media', recursive=True),
        ),
    ]
