# Generated by Django 4.1.7 on 2023-03-10 14:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tiqo_parser', '0013_attachment_url_qonto_alter_attachment_filepath'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTransfer',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('beneficiary_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiqo_parser.contact')),
            ],
        ),
    ]
