# Generated by Django 4.1.7 on 2023-03-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiqo_parser', '0015_externaltransfer_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('M', 'membership'), ('B', 'beneficiarie')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
