# Generated by Django 4.1.7 on 2023-03-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiqo_parser', '0016_contact_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externaltransfer',
            old_name='beneficiary_id',
            new_name='beneficiary',
        ),
    ]
