# Generated by Django 4.1.7 on 2023-03-10 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiqo_parser', '0017_rename_beneficiary_id_externaltransfer_beneficiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_transactions', to='tiqo_parser.contact'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='uuid_external_transfer',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='initiator_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiator_transactions', to='tiqo_parser.contact'),
        ),
        migrations.DeleteModel(
            name='ExternalTransfer',
        ),
    ]
