# Generated by Django 4.1.7 on 2023-03-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiqo_parser', '0020_rename_first_name_odoocontact_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='QontoContact',
        ),
    ]
