# Generated by Django 4.1.7 on 2023-03-11 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiqo_parser', '0022_rename_initiator_id_transaction_initiator'),
    ]

    operations = [
        migrations.AddField(
            model_name='qontocontact',
            name='odoo_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiqo_parser.odoocontact'),
        ),
    ]
