# Generated by Django 4.1.7 on 2023-03-12 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiqo_parser', '0024_odooarticles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'Label Qonto', 'verbose_name_plural': 'Labels Qonto'},
        ),
        migrations.AlterModelOptions(
            name='qontocontact',
            options={'verbose_name': 'Contact Qonto', 'verbose_name_plural': 'Contacts Qonto'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction Qonto', 'verbose_name_plural': 'Transactions Qonto'},
        ),
        migrations.AddField(
            model_name='label',
            name='odoo_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiqo_parser.odooarticles'),
        ),
        migrations.AlterField(
            model_name='qontocontact',
            name='type',
            field=models.CharField(choices=[('M', 'User Qonto'), ('B', 'Bénéficiaire')], max_length=1),
        ),
    ]
