# Generated by Django 4.1.7 on 2023-03-13 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiqo_parser', '0026_alter_iban_options_transaction_odoo_invoice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='odoo_journal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiqo_parser.accountjournal'),
        ),
    ]
