# Generated by Django 4.1.7 on 2023-03-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiqo_parser', '0027_label_odoo_journal_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
