# Generated by Django 4.1.7 on 2023-03-14 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiqo_parser', '0029_accountaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='odoo_account_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiqo_parser.accountaccount'),
        ),
    ]
