# Generated by Django 4.1.7 on 2023-03-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiqo_parser', '0030_label_odoo_account_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountaccount',
            name='code',
            field=models.CharField(default='azeae', max_length=100),
            preserve_default=False,
        ),
    ]
